setwd("/home/dario/Documenti/RNA_seq/RNA_lncSeq/RNA_Sequencing")
load("Human_logitModel.RData")
test <- read.table(file="novelProtein.dat",sep="\t",col.names=c("ID","mRNA","ORF","Fickett","Hexamer"))
test$prob <- predict(mylogit,newdata=test,type="response")
attach(test)
output <- cbind("mRNA_size"=mRNA,"ORF_size"=ORF,"Fickett_score"=Fickett,"Hexamer_score"=Hexamer,"coding_prob"=test$prob)
write.table(output,file="novelProtein",quote=F,sep="\t",row.names=ID)
